### ISSUE TITLE
Increase the Thumbnail Size on Mobile

### ISSUE THREAD

**Issue by ghost** [AlxMedia/boxstyle#3]
Hi, 
THANK YOU SO MUCH 💓 for this awesome theme !
I like almost every feature included with this theme ... 

If you can implement a feature to increase the Thumbnail size for posts on mobile ... That would be 👌 awesome ...
![Screenshot_20220906-165549_Firefox](https://user-images.githubusercontent.com/88363715/188617916-668f37ae-b8f8-41c7-96f5-de62c3a9ba46.jpg)

TIA ..

**Comment by AlxMedia** [comment]
Hi!

Try adding this in Customize > Additional CSS:

`
@media only screen and (max-width: 479px) {
.post-list .post-thumbnail { max-width: 240px; }
}
`

**Comment by ghost** [comment]
Thank 😊 You .. Boss !
